apiVersion: apps/v1
kind: Deployment
metadata:
  name: much-todo-backend
  namespace: starttech

spec:
  replicas: 2

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  selector:
    matchLabels:
      app: much-todo-backend

  template:
    metadata:
      labels:
        app: much-todo-backend

    spec:
      containers:
        - name: backend

          image: 405872562779.dkr.ecr.us-east-1.amazonaws.com/starttech-backend-api:v2

          imagePullPolicy: Always

          ports:
            - containerPort: 8080

          envFrom:
            - configMapRef:
                name: backend-config

            - secretRef:
                name: much-todo-backend-secret

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"

          livenessProbe:
            httpGet:
              path: /api/ping
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15

          readinessProbe:
            httpGet:
              path: /api/ping
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10