apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: starttech

type: Opaque

stringData:
  MONGO_URI: "mongodb+srv://ogeleayotunde_db_user:7hSc5OVafx8ALDFY@cluster0.r5lvxzl.mongodb.net/?appName=Cluster0"